### ISSUE TITLE
[01] - Deverá ser possível consultar os movimentos da conta selecionada

### ISSUE THREAD

**Issue by marcio-santos-deel** [pucrs-gcs-2020-1/trabalho1-20201-we_work#1]
- [ ] Todos os movimentos
- [ ] Movimentos filtrados por período (data inicial e final)
- [ ] Movimentos filtrados por operador
- [ ] Movimentos filtrados por tipo (receita ou despesa)

**Comment by leocanto** [comment]
Verificado.
