### ISSUE TITLE
[20] - Relatorio_WeWork

### ISSUE THREAD

**Issue by RobAndEdu** [pucrs-gcs-2020-1/trabalho1-20201-we_work#20]
Confecção relatório do trabalho

**Comment by wendelldelacerda** [comment]
- [x]  Folha de rosto com nomes completos dos componentes do time;

- [x] Descrição clara do fluxo de trabalho adotado (pode ser uma variação dos fluxos vistos
em aula, adaptado pelo time).

- [x] Demonstração de que o time seguiu o fluxo definido. Pode conter capturas de tela e
descrições.

- [x] Conclusão contendo reflexões sobre as dificuldades encontradas, como foram superadas
e quais as lições aprendidas.
